workspace(name = "basic")

# When using in your project, this can be a direct cut-n-paste, however you should replace the
# local_repository with a http_archive() block similar to the following, using the version and
# sha256 matching your desired release
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
#
# http_archive(
#    name = "rules_jq",
#    sha256 = "52771b5f7fb5017b0f5a3816b46624d2b9a336ddc178b261de988d969cd329d8",
#    url = "https://github.com/jqlang/bazel_rules_jq/releases/download/0.0.1/bazel_rules_jq-v0.0.1.tar.gz",
#)

local_repository(
    name = "rules_jq",
    path = "../..",
)

load("@rules_jq//jq:repositories.bzl", "jq_register_toolchains", "rules_jq_dependencies")

rules_jq_dependencies()

jq_register_toolchains(
    name = "jq",
    jq_version = "1.6",
)
