---
# cSpell Settings

# Done in YAML rather than JSON because -- like XML -- there is a cleary-documented way to write
# comments that don't hit-or-miss fail on some parsers.  We're miles ahead of XML with JSON;
# someday, JSON will even reach parity!

version: "0.2"

# flagWords - list of words to be always considered incorrect
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the"
flagWords:
  - hte

language: en

# words - list of words to be always considered correct: an Allowlist per-se
words:
  - allanc
  - bazel
  - bazelisk
  - bazelrc
  - bzlmod
  - chickenandpork
  - ibazel
  - jqlang
  - ruleset
  - slamdev
  - starlark
